add kubernetes kill pod notebook
chaosiq/rtk-notebooks pull request #3
Opened 2020-10-02 16:05 UTC by gtfisher

Signed-off-by: gtfisher <grant@chaosiq.io>

2020-10-05 09:35 UTC, russmiles requested changes
I haven't had a chance to actually run anything during this first pass review, sorry! Instead I was focussed on how the mission was explained as that is crucial to making these artifacts engaging and exciting to our audience. Happy to jump on a call @gtfisher to explain myself better.

2020-10-05 09:35 UTC, russmiles commented on kubernetes-kill-pod/README.md
> +# Notebook for Killing a Kubernetes POD
Ideally this should be in the form we've talked about when it comes to naming a "mission", see https://chaosiq.slack.com/archives/CH4G2AS2D/p1601552023008800

2020-10-05 09:35 UTC, russmiles commented on kubernetes-kill-pod/README.md
> +Resources for viewing and running a notebook to kill a kubernetes POD with the
This needs to explain a few things, such as:

* What you're going to do, in summary.
* What super power practice you're going to learn and flex.
* Why this is important.

2020-10-05 09:35 UTC, russmiles commented on kubernetes-kill-pod/README.md
> +## Running the Notebook
Try and make the titles a little less literal and a little more engaging? Rather than "Running the Notebook", how about "Before you start this mission", or "Mission Prep"? The fact it _is_ a notebook should be downplayed a little as that is the mechanics of the experience, but not the experience.

2020-10-05 09:35 UTC, russmiles commented on kubernetes-kill-pod/README.md
> +Chaos Toolkit.
And Reliably?

2020-10-05 09:35 UTC, russmiles commented on kubernetes-kill-pod/README.md
> +Chaos Toolkit.
In fact, this should really be "with Reliably and the Chaos Toolkit". It's hard when we don't have "reliably" in situ yet, but we should be also looking to imagine how cool this mission could be with features Reliably could have. It will help us prioritise the implementation of those features across the Reliably platform.

2020-10-05 09:35 UTC, russmiles commented on kubernetes-kill-pod/README.md
> +### Running the notebook with Visual Studio Code
You need to either pick one way, or explain that there is more than one way to execute this mission, and why, how to pick the right one for you, and perhaps even a preferential option as far as Reliably is concerned?

2020-10-07 11:02 UTC, gtfisher commented on kubernetes-kill-pod/README.md
> +Chaos Toolkit.
Changed title in Readme

2020-10-07 11:07 UTC, gtfisher commented on kubernetes-kill-pod/README.md
> +Resources for viewing and running a notebook to kill a kubernetes POD with the
I think this should be part of the notebook file rather that the README

2020-10-07 11:08 UTC, gtfisher commented on kubernetes-kill-pod/README.md
> +### Running the notebook with Visual Studio Code
updated

2020-10-07 11:23 UTC, merged